EMBED_COLOR_PRIMARY = 0x5865F2
EMBED_COLOR_SUCCESS = 0x2ECC71
EMBED_COLOR_WARNING = 0xE67E22
EMBED_COLOR_DANGER = 0xE74C3C

SUMMARY_BATCH_SIZE = 20
SUMMARY_FETCH_MAX_MESSAGES = 20

DISCORD_EMBED_DESCRIPTION_LIMIT = 3900
DISCORD_FOLLOWUP_CHUNK_SIZE = 1900

WEATHER_DEFAULT_LOCATION = "Da Nang"
WEATHER_FORECAST_MAX_DAYS = 3

DEFAULT_SM2_EASINESS = 2.5
DEFAULT_SM2_INTERVAL = 1
DEFAULT_SM2_REPETITION = 0
MIN_SM2_EASINESS = 1.3
